version: '3.1'

services:
  db:
    build: ./db
    restart: always
    env_file:
      - .env
    volumes:
      - /db/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db