exports.ORDER = {
	WAIT_FOR_PAYMENT: 'WAIT_FOR_PAYMENT',
	CONFIRMED_PAYMENT: 'CONFIRMED_PAYMENT',
	IN_PACKING_PROCESS: 'IN_PACKING_PROCESS',
	IN_SHIPPING_PROCESS: 'IN_SHIPPING_PROCESS',
	COMPLETED_SHIPPING: 'COMPLETED_SHIPPING'
}
exports.ROLE = {
	CUSTOMER: 'CUSTOMER',
	STAFF: 'STAFF',
	ADMIN: 'ADMIN'
}
